### PR TITLE
removes the enclave outlaw loadout

### PR DESCRIPTION
**Pull request by Mannybrado**
## About The Pull Request
I'm under the impression that this is something the loremaster wants.

## Why It's Good For The Game
Not within the vision of the server; LRP as shit.

## Changelog
:cl:
del: enclave loadout
/:cl:

### CODE REVIEW

**Review by Pebblesthe2nd — APPROVED** [review]
Green light from me, no code issues:
EDIT its not a good idea for me to review this on second thought Roh, I have become rather biased against Enclave to be honest due to the headaches they have caused, and will not oppose any removal of code related to them at this point, quite the transformation from happily making content for them at the start. I should recluse myself.

**Comment by Rohesie** [comment]
> 
> 
> Green light from me, no code issues:
> EDIT its not a good idea for me to review this on second thought Roh, I have become rather biased against Enclave to be honest due to the headaches they have caused, and will not oppose any removal of code related to them at this point, quite the transformation from happily making content for them at the start. I should recluse myself.

We'll run this through the lore nerds, don't worry.

**Comment by EgorDinamit** [comment]
I wonder how exactly this benefits anyone. If anything, you will now have to wonder if "that random outlaw" is a part of Enclave or not.
Good luck, we'll just have 10 outlaws running in random loadouts and black paint now.

**Comment by dawsonkeyes** [comment]
> I wonder how exactly this benefits anyone. If anything, you will now have to wonder if "that random outlaw" is a part of Enclave or not.
> Good luck, we'll just have 10 outlaws running in random loadouts and black paint now.

they're not because there's no enclave here and they died in navarro

**Comment by EgorDinamit** [comment]
> > I wonder how exactly this benefits anyone. If anything, you will now have to wonder if "that random outlaw" is a part of Enclave or not.
> > Good luck, we'll just have 10 outlaws running in random loadouts and black paint now.
> 
> they're not because there's no enclave here and they died in navarro

Everyone can't die in a single camp. Navarro is but a place, Enclave is idea and a giant organization with its history going from pre-war times.

**Comment by SpaceSlug2** [comment]
FUCKING WHAT?

**Comment by SpaceSlug2** [comment]
> > I wonder how exactly this benefits anyone. If anything, you will now have to wonder if "that random outlaw" is a part of Enclave or not.
> > Good luck, we'll just have 10 outlaws running in random loadouts and black paint now.
> 
> they're not because there's no enclave here and they died in navarro

Words from a man who's clearly never played Fallout 3, New Vegas, 4, and maybe even fucking fallout 76

**Comment by EgorDinamit** [comment]
> > > I wonder how exactly this benefits anyone. If anything, you will now have to wonder if "that random outlaw" is a part of Enclave or not.
> > > Good luck, we'll just have 10 outlaws running in random loadouts and black paint now.
> > 
> > 
> > they're not because there's no enclave here and they died in navarro
> 
> Words from a man who's clearly never played Fallout 3, New Vegas, 4, and maybe even fucking fallout 76

Man, there is a reason those morons consider Fallout 3, 4 and 76 non-canon on this server, lol.
They are just tired of making up valid lore reasons for anything they do.

**Comment by SpaceSlug2** [comment]
> > > > I wonder how exactly this benefits anyone. If anything, you will now have to wonder if "that random outlaw" is a part of Enclave or not.
> > > > Good luck, we'll just have 10 outlaws running in random loadouts and black paint now.
> > > 
> > > 
> > > they're not because there's no enclave here and they died in navarro
> > 
> > 
> > Words from a man who's clearly never played Fallout 3, New Vegas, 4, and maybe even fucking fallout 76
> 
> Man, there is a reason those morons consider Fallout 3, 4 and 76 non-canon on this server, lol.
> They are just tired of making up valid lore reasons for anything they do.

Staff and coders after the poll: “Fuck the players, remove the Enclave, and while you’re at it fuck over oasis!”

**Comment by EgorDinamit** [comment]
@SpaceSlug2 well, if you are still interested in the Enclave stuff, we've been working on a new server based off this codebase.
If you want, I could send you the link to repository and Discord invite, since Fortune13 is obviously 100% against all fun.

**Comment by SpaceSlug2** [comment]
> @SpaceSlug2 well, if you are still interested in the Enclave stuff, we've been working on a new server based off this codebase.
> If you want, I could send you the link to repository and Discord invite, since Fortune13 is obviously 100% against all fun.

Sure

**Comment by EgorDinamit** [comment]
@SpaceSlug2 
https://github.com/vlggms/fortune13
https://discord.gg/CpYhRXwXfg

**Comment by Rohesie** [comment]
> 
> 
> @SpaceSlug2 well, if you are still interested in the Enclave stuff, we've been working on a new server based off this codebase.
> If you want, I could send you the link to repository and Discord invite, since Fortune13 is obviously 100% against all fun.

Consider working on Mojave Sun. They have a pretty nice codebase and a different approach than Fortune 13.

**Comment by SpaceSlug2** [comment]
> > @SpaceSlug2 well, if you are still interested in the Enclave stuff, we've been working on a new server based off this codebase.
> > If you want, I could send you the link to repository and Discord invite, since Fortune13 is obviously 100% against all fun.
> 
> Consider working on Mojave Sun. They have a pretty nice codebase and a different approach than Fortune 13.

I’m not THAT good of a coder to be able to work on Mojave Sun

**Pull request merged**
