### PR TITLE
New Oasis

### PR DESCRIPTION
**Pull request by Wirpy**
## About The Pull Request

Oasis Rework, it's lit.
whole thread on the discord for those interested

## Why It's Good For The Game

stopgap oasis sucks

c2ca1596d2854f42f5abf4102e1c30fe

stopgap oasis sucks

## Changelog
:cl:
tons of shit
/:cl:

### CODE REVIEW

**Comment by cornercube** [comment]
just minor suggestions

**Comment by Mannybrado** [comment]
way too big, no path should loop on itself. its already a pain in the ass to keep watch on the town, this makes it significantly harder to defend. meh.

**Comment by skateboardjones** [comment]
Should wait for the actual rework. Likely best to simply revert what we have now to what it was before, and, again, wait for the actual rework.

**Comment by ThyBaron** [comment]
Let's wait before merging this one, there's a few other reworks underway. Once they're done we can compare and vote.

**Comment by Wirpy** [comment]
dd0a15632976ca887dea07390c099bce

**Pull request closed without merging**
