### PR TITLE
Camp Miller redux

### PR DESCRIPTION
**Pull request by KillerGryphon**
## About The Pull Request

Citizens and Soldiers of the NCR! We've gotten shipments from Quarry Junction, it's time the fortifications were improved, and corrections made! Now, the Republic has seen to it that Camp Miller be given the advancements an advanced military needs, along with a whole host of improvements and changes! See the following images.

new NCR area and houses
NCR Barracks, Warroom, and quarters
NCR Mess and Armory
NCR Prison, gym, and botany
NCR medbay and mining area
NCR gatehouse, pond, and parking lot

Unfortunately, doing all this work has roused up some "locals", and we've taken some measures to block off the worst of it, but keep your weapons close outside the base!

NCR tunnel to north bunker
NCR road south
NCR houses south of base

## Why It's Good For The Game

I've spoken to several NCR players, and even outside of the NCR, the common opinion was that the NCR base needed to be changed. This is my take at it! Discord user Kneesocks made an excellent point about how NCR are at an inherent disadvantage when defending their base normally, the UI covers most of the bottom, and they're in the top left of the map! The solution: make it go west to east instead! With the new additions of being able to make concrete, I've decided the NCR would be taking advantage of that ASAP, and fortifying their base, with some help from lore friendly concrete quarries helping out! 

A big thing to be pointed out, no longer shall the NCR have an underground fortified area! The captain and ranger's quarters are shrunk down and made into offices, all topside. The Captain and Veteran also have money at their desks to compensate for the Legion also having money at theirs! Speaking of money, the 0.4 conversion rate for dollars meant that the pay vault needed to give more money, so I have adjusted it to pay more, since you're getting paid less, so NCR isn't screwed over since their money they carry already got screwed over.

In addition, new houses, new areas to RP in, new routes to take, and new ways to break into the NCR base! Change is good, and I hope you all think this map is good as well!

### CODE REVIEW

**Comment by Mannybrado** [comment]
Add in a door to the shooting range, as well as a crate with extra targets in it. 
Put some indents and out-croppings into the giant flat rock-face areas to make it look more natural, also try and put some cracked sidewalks in that area as well so it doesn't look so bland. 
Face the sleeper in the infirmary north. (right click and hit "generate icon from directions" in the selection menu or something, make sure its directions though)
image
Move the MP stuff into a separate room, like that.
The gate.... sucks. To be honest. I don't really see a better way of doing without moving the entrance of the base further south, though.

all in all pretty good. yep

**Comment by thedarkcrusader** [comment]
Replace some of those lockers in the  Prison with  normal gun lockers with nothing inside used when storeing guns for holding or whatever would also put 1 or 2 in the armory as well

**Comment by KillerGryphon** [comment]
> Add in a door to the shooting range, as well as a crate with extra targets in it.
> Put some indents and out-croppings into the giant flat rock-face areas to make it look more natural, also try and put some cracked sidewalks in that area as well so it doesn't look so bland.
> Move the MP stuff into a separate room, like that.
I will do all of these suggestions, thanks! 

> The gate.... sucks. To be honest. I don't really see a better way of doing without moving the entrance of the base further south, though.
Honestly, I'm not happy with it either. I think that guy who said "get rid of all gates" had a point. I'll remove it tomorrow.

**Comment by KillerGryphon** [comment]
> Replace some of those lockers in the Prison with normal gun lockers with nothing inside used when storeing guns for holding or whatever would also put 1 or 2 in the armory as well

Can do this, no problem!

**Comment by KillerGryphon** [comment]
Okay, made all those changes, here are some bad cellphone photos. In addition, discovered I'd made a serious error, and forgot some spawns! Fixed all that, now all NCR roles have landmarks.

**Comment by KillerGryphon** [comment]
Apparently I copied the Corporal's landmark and pasted that for the bunks... and didn't include Rear Echelon or even troopers. MPs are added in their area, and now medics are as well. This is why we test things

**Comment by Pebblesthe2nd** [comment]
Maybe it's just me but it seems a teeny tiny bit  unbalanced to give NCR a pay equal to around 230-280 caps vs the Legion pay of around 80 caps.

**Comment by KillerGryphon** [comment]
Reverted the change, pebbles.

**Comment by Pebblesthe2nd** [comment]
I'll try to figure out why the spawner labels are lying, but if its not (easily) fixable we could just set a fixed pay rate and be done with it.

**Pull request closed without merging**
