### PR TITLE
Adds potential player bases for RP

### PR DESCRIPTION
**Pull request by Keksk**
## About The Pull Request
Adds housing.

## Screenshots

grafik

grafik

grafik

### CODE REVIEW

**Comment by Hyperstellarwithguns** [comment]
these all look pretty great, especially love the bottom one with the li'l fishing pond.
also nice touch how they're (almost) all under ground so they don't take up too much space on the surface, grade A stuff

**Comment by EgorDinamit** [comment]
Ah yes, the new Enclave base.

**Comment by Keksk** [comment]
> 
> 
> Ah yes, the new Enclave base.

kek

**Comment by thedarkcrusader** [comment]
Wr dont need more  fuckshscks

**Pull request merged**
