### PR TITLE
Wirpy's Chicken Ranch

### PR DESCRIPTION
**Pull request by Wirpy**
## About The Pull Request

Replaces a pretty much unused wooden house with a brand new improved Chicken Ranch that we all miss and loved dearly when we had it!

## Why It's Good For The Game

It adds a bar location which is not inside faction terrortority, making it a non-faction aligned bar which could be taken over by pretty much everyone. A nice gathering spot for players who wish to create a central bar/kitchen area type shop thing and run it which will hopefully promote roleplay by adding a non-aligned bar hotspot. 

Alongside that It's also worth clearing out both roleplay wise and lootwise due to the presence of the raider boss. 
I also made the area around It's location look a bit nicer which will make the overall feel of that part of the map look better. 

ed1b3ade26d5657d60e5878f09e68f69

## Changelog
:cl:
remove: brahmins north of it since raiders got aggroed by them 
add: Tidied up the area around it's location
add: Chicken Ranch Location
/:cl:

### CODE REVIEW

**Comment by thedarkcrusader** [comment]
No mo strip clubs

**Comment by Wirpy** [comment]
> No mo strip clubs

WE NEED CHICKEN RANCH

**Comment by thedarkcrusader** [comment]
> > No mo strip clubs
> 
> WE NEED CHICKEN RANCH

NO WE DON TTTT

**Comment by Keksk** [comment]
I looked over the PR. Looks neat and the abandoned farm above it now finally could have more use!
1.)However I'd remove the ranged raiders + raider boss. Lots of folk walk past that street and will most definitely pull all the mobs into oasis. Just keep the melee variants of them all.
2.) You forgot an area spot:
grafik

**Comment by Wirpy** [comment]
183d03439eca2143a0ea7e9a09534b17

cf9c601339412965f174eb526697e3ba

**Pull request merged**
