### PR TITLE
Oasis-Den Rework [Now READY!]

### PR DESCRIPTION
**Pull request by Wirpy**
## About The Pull Request

Reworks the Den and Oasis, making them better map-wise and make more sense. And look better (Mostly for the Den since Oasis looks good in my opinion already) 

## Why It's Good For The Game
-Fixes the awfull mess the current underground z-level is by properly aligning ladders and shit to the underground (expect followers cause its god damm huge their underground part) 
-Removes the Oasis Underground, adding it's underground stuff to the topside
-Oasis Underground is now replaced by a reworked Den, placing it dead center almost of the underground. Entrance is now at old spot north of oasis, to the left at the crossroads with gallows. 
-Den gets buffed by the addition of a Clinic and Botanical area, making them feel more like a ruling faction of the outlaw underground.
-Player shop shacks added to the Den, players can now take over already made shop shacks to create their own shops right outside the Den shop creating a hotspot for a player driven economy!
-Den Bar is mostly kept the same but with the removal of the fight cage and addition of dorm rooms for rent (up to players really)
-Also moved some stuff around in the Bar making it look better and so forth.
-New pathways and opens up the underground creating more ways to travel the underground
-Adds a few new sprites I used for the Den flooring
-Brings back the reason to play the Khans via the addition of a Khan base in the Den with a chemistry room, botanical area and armory. 

f7146b134b934d0f7b85b4e808886a20

0068f00e7bf39731b84535056665a02b

## Changelog
:cl:
add: A lot of shit
/:cl:

### CODE REVIEW

**Comment by zuliouse** [comment]
As someone who's been playing Oasis almost exclusively lately, I'm not sure this is the best idea. Putting Outlaws _inside_ the town's walls would make it nearly impossible to maintain order. How can you exile criminals from Oasis when they literally spawn there? I think this will put an unnecessary strain on what is already a pretty chaotic town. Oasis and Den are active enough as it is. While the idea of a criminal underbelly is certainly compelling, I worry about the actual practical effect this will have on the faction itself

**Comment by Keksk** [comment]
I love a few aspects of this PR!
Having the Shop being linked to his mansion would allow the Shopkeeper to actually move in between the two buildings more freely. The overhaul of the Den building looks fantastic, making it appear less open-spaced and large. Overall the new appearance of the Den appears to suit the faction much more, but that’s subjective.
However I wouldn't merge the two factions together given they have completely different mindsets and goals in a round. This might cause a lot of conflict between the two factions and while I believe conflict keeps things fresh, I don't think this would be the right way to approach that subject.I'd also leave the old khan base in it.

**Comment by Wirpy** [comment]
> I love a few aspects of this PR!
> Having the Shop being linked to his mansion would allow the Shopkeeper to actually move in between the two buildings more freely. The overhaul of the Den building looks fantastic, making it appear less open-spaced and large. Overall the new appearance of the Den appears to suit the faction much more, but that’s subjective.
> However I wouldn't merge the two factions together given they have completely different mindsets and goals in a round. This might cause a lot of conflict between the two factions and while I believe conflict keeps things fresh, I don't think this would be the right way to approach that subject.I'd also leave the old khan base in it.



> As someone who's been playing Oasis almost exclusively lately, I'm not sure this is the best idea. Putting Outlaws _inside_ the town's walls would make it nearly impossible to maintain order. How can you exile criminals from Oasis when they literally spawn there? I think this will put an unnecessary strain on what is already a pretty chaotic town. Oasis and Den are active enough as it is. While the idea of a criminal underbelly is certainly compelling, I worry about the actual practical effect this will have on the faction itself.

After some thinking I've seperated den/oasis making the entrance to sewers north of Oasis as it used to be. 
Oasis no longer has no underground expect prospectors. 
The important parts of the oasis underground has been added to the topside intergrating with buildings already there and extended oasis a bit south to fit some stuff for deputies/sheriff.

**Comment by Wirpy** [comment]
641a24a2d4cf3146ed1b5232860420f2
7ebdbf3a25064a0b57a6d1799daabf74

**Comment by Wirpy** [comment]
031dba4ccc973a2a2458ae8f6c202451

**Comment by Mannybrado** [comment]
uhh. can you get rid of the tree from the den? please? its kind of... stupid?

**Comment by Keksk** [comment]
Suggested changes: 

1. Gives deputies a place to sit down and RP while also watching the prisoners.
grafik
2.Add a door to the shop for convenience. Also remove space tiles underneath the vendors.
grafik
3. Return the old khan base. A little edit to the farm portion of the den doctor portion. A dead tree instead of a living one.
grafik
4. Have a little outside area for the bar.
grafik

**Pull request closed without merging**
