### PR TITLE
Deputy: transform and loadout

### PR DESCRIPTION
**Pull request by cornercube**
## About The Pull Request

Gives the town deputy different loadout options
the Frontier load out: retains the original trail carbine, deputy coat and hat, and has their .357 changed to a .44 to match ammo types like a true cowboy
The Police loadout: gets a police shotgun, police revolver, a police outfit, and loses head protection in favor of a bulletproof vest.  so you can be space officer o'hara
the PMC load out: proudly wears the olive-drab attire of the Oasis militia, and is equipped with a type I vest, an old fashioned security helmet, and his worn-down 10mm SMG

## Why It's Good For The Game

deputy is outgunned and out-fashioned by their enemies
while a mob of black coated deputies with cowboy guns is amusing in and of itself, we do want to give options to players if they want a bit more leeway in how they can choose to look, at the least the mob enforcers can choose between a vest or chem coat

## Changelog
:cl:
add: 3 (actually 2) new deputy loadouts
tweak: deputy has no weapons on his person on spawn, gets all relevant equipment from his loadout

### CODE REVIEW

**Review by Pebblesthe2nd — COMMENTED** [review]
Like the idea, Oasis law needs a breath of fresh air.
Would request you change the greasegun to something else though, perhaps a worn 10mm SMG? This to keep the faction themes clearly separated, Legion is the only faction with greasegun in loadout, no point intruding on that, could slap in a UZI also for another alternative.

**Comment by cornercube** [comment]
> Like the idea, Oasis law needs a breath of fresh air.
> Would request you change the greasegun to something else though, perhaps a worn 10mm SMG? This to keep the faction themes clearly separated, Legion is the only faction with greasegun in loadout, no point intruding on that, could slap in a UZI also for another alternative.

roger that
grease gun was a placeholder anyways
uzi is the dens weapon, due to being 80s yakuza weapon of choice

worn 10mm sounds good, ill look for it

**Comment by cornercube** [comment]
M3A1 replaced with the worn 10mm SMG
side arm replaced with a switchblade as well, maybe the police loadout should get a baton?

**Comment by cornercube** [comment]
M3A1 replaced with the worn 10mm SMG
side arm replaced with a switchblade as well, maybe the police loadout should get a baton?

**Comment by Pebblesthe2nd** [comment]
> M3A1 replaced with the worn 10mm SMG
> side arm replaced with a switchblade as well, maybe the police loadout should get a baton?

Love it =)   Maybe, baton is a bit wonky, its still running citcode and its a bit of a mess, unsure how to grade it on a power scale. I don't see any harm in trying it though, AFAIK the sheriff and the NCR MP already have batons so its not game breaking either way (+ couple more telebatons thats essentially the same). If your gut says baton go for it, its a wooden stick, super easy to manufacture so certainly would fit. Either that or the Louisville =D

**Comment by cornercube** [comment]
> that or the Louisville =D
running around with a bat sounds more like the den mob, but its god damn hilarious to imagine the town dispensing justice with a swatter

ill add it for now, ill just PR it away if we get too many complaints
and put "new non-janky baton" on my to-do list

**Pull request merged**
