### PR TITLE
new shipment of rotgut, straight from redding

### PR DESCRIPTION
**Pull request by cornercube**
## About The Pull Request

adds FO2 drink, Rotgut
essentially whiskey with the kitchen sink it

when sprite is ready, i was told to use icon path: icon_state = "rotgut", currently a whiskey glass

## Why It's Good For The Game

more fallout-flavor
new way for the barkeep to doctor his drinks and kill you, sending you to the doctor across the street

## Changelog

add: Rotgut
add: Rotgut recipe 
add: Rotgut bottle 
Tweak: champagne renamed to Lead champagne, an in-universe brand

### CODE REVIEW

**Comment by Pebblesthe2nd** [comment]
The bottle art is in, icons/fallout/objects/food&drinks/drinks.dmi    named "rotgut"
If you wanna add a bottle object or use the bottle art for the glass is up to you. To use it for the glass you'll need to add
the icon path of course.

**Comment by cornercube** [comment]
> The bottle art is in, icons/fallout/objects/food&drinks/drinks.dmi named "rotgut"
> If you wanna add a bottle object or use the bottle art for the glass is up to you. To use it for the glass you'll need to add
> the icon path of course.

I'll probably add the bottle then, keeping it the glass as a whiskey glass is fine for now
then I'll have to add rotgut bottles to wasteland spawn loot too

**Comment by Mannybrado** [comment]
ehm sir................................................................................................................ill have you know that redding was actually destroyed by the brotherhood in lore........................................................................................................................so basically get owned............................................................................................................................................................

**Comment by cornercube** [comment]
> ehm sir................................................................................................................ill have you know that redding was actually destroyed by the brotherhood in lore........................................................................................................................so basically get owned............................................................................................................................................................

their gold mines were destroyed, but the town itself survived
chief hanlon will retire there and become its mayor in one ending

but in FO2 redding is one of the places you can acquire rotgut, the other being broken hill, which actually did fall apart

**Pull request merged**
